[project]
name = "opensentry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "face-recognition>=1.3.0",
    "flask>=3.1.2",
    "opencv-python>=4.12.0.88",
    "ultralytics>=8.3.204",
    "zeroconf>=0.148.0",
]
